# Q8. Group-Based Insights (Customer Segmentation Logic)
**Context:** ML models often depend on aggregated patterns.
**Dataset:** Tips

In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

tips = sns.load_dataset('tips')
print('Shape:', tips.shape)
tips.head()

Shape: (244, 7)

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

## Task 1a: Average Tip by Day

In [3]:
avg_tip_by_day = tips.groupby('day')['tip'].mean().round(2)
print('Average Tip by Day:')
print(avg_tip_by_day)

Average Tip by Day:
day
Thur    2.77
Fri     2.73
Sat     2.99
Sun     3.26
Name: tip, dtype: float64

/var/folders/sz/zndxrfn90kx0h_ydhc2_f8xc0000gn/T/ipykernel_7201/2740346340.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  avg_tip_by_day = tips.groupby('day')['tip'].mean().round(2)

## Task 1b: Total Bill by Gender

In [4]:
total_bill_by_gender = tips.groupby('sex')['total_bill'].agg(['sum', 'mean', 'count']).round(2)
total_bill_by_gender.columns = ['Total Bill ($)', 'Avg Bill ($)', 'Num Transactions']
print('Total Bill Summary by Gender:')
print(total_bill_by_gender)

Total Bill Summary by Gender:
        Total Bill ($)  Avg Bill ($)  Num Transactions
sex
Male           3256.82         20.74               157
Female         1570.95         18.06                87

/var/folders/sz/zndxrfn90kx0h_ydhc2_f8xc0000gn/T/ipykernel_7201/320129142.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  total_bill_by_gender = tips.groupby('sex')['total_bill'].agg(['sum', 'mean', 'count']).round(2)

## Task 2: Create New Feature — tip_percentage

In [5]:
tips['tip_percentage'] = (tips['tip'] / tips['total_bill'] * 100).round(2)

print('tip_percentage stats:')
print(tips['tip_percentage'].describe().round(2))
print()
print('Sample rows with new feature:')
tips[['total_bill', 'tip', 'tip_percentage']].head(8)

tip_percentage stats:
count    244.00
mean      16.08
std        6.11
min        3.56
25%       12.91
50%       15.48
75%       19.15
max       71.03
Name: tip_percentage, dtype: float64

Sample rows with new feature:

   total_bill   tip  tip_percentage
0       16.99  1.01            5.94
1       10.34  1.66           16.05
2       21.01  3.50           16.66
3       23.68  3.31           13.98
4       24.59  3.61           14.68
5       25.29  4.71           18.62
6        8.77  2.00           22.81
7       26.88  3.12           11.61

## Task 3: Which Day Has the Highest Tipping Behavior?

In [6]:
day_tipping = tips.groupby('day').agg(
    avg_tip_pct=('tip_percentage', 'mean'),
    avg_tip_amt=('tip', 'mean'),
    num_customers=('tip', 'count')
).round(2)

best_day = day_tipping['avg_tip_pct'].idxmax()
print(f'Day-wise Tipping Summary:')
print(day_tipping)
print(f'\nHighest Tipping Day: {best_day} ({day_tipping.loc[best_day, "avg_tip_pct"]}% avg tip)')

Day-wise Tipping Summary:
      avg_tip_pct  avg_tip_amt  num_customers
day
Thur        16.13         2.77             62
Fri         16.99         2.73             19
Sat         15.31         2.99             87
Sun         16.69         3.26             76

Highest Tipping Day: Fri (16.99% avg tip)

/var/folders/sz/zndxrfn90kx0h_ydhc2_f8xc0000gn/T/ipykernel_7201/3193660352.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  day_tipping = tips.groupby('day').agg(