# Q9. Advanced Filtering + Subsetting
**Context:** Training data is often filtered based on business rules.
**Dataset:** Tips

In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

tips = sns.load_dataset('tips')
print('Original dataset shape:', tips.shape)
tips.head()

Original dataset shape: (244, 7)

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

## Task 1: Filter — total_bill > 20 AND tip < 3

In [2]:
mask = (tips['total_bill'] > 20) & (tips['tip'] < 3)
filtered_df = tips[mask].copy()

filtered_df

     total_bill   tip     sex smoker   day    time  size
21        20.29  2.75  Female     No   Sat  Dinner     2
33        20.69  2.45  Female     No   Sat  Dinner     4
48        28.55  2.05    Male     No   Sun  Dinner     3
57        26.41  1.50  Female     No   Sat  Dinner     2
68        20.23  2.01    Male     No   Sat  Dinner     2
102       44.30  2.50  Female    Yes   Sat  Dinner     3
113       23.95  2.55    Male     No   Sun  Dinner     2
119       24.08  2.92  Female     No  Thur   Lunch     4
129       22.82  2.18    Male     No  Thur   Lunch     3
131       20.27  2.83  Female     No  Thur   Lunch     2
153       24.55  2.00    Male     No   Sun  Dinner     4
166       20.76  2.24    Male     No   Sun  Dinner     2
187       30.46  2.00    Male    Yes   Sun  Dinner     5
192       28.44  2.56    Male    Yes  Thur   Lunch     2
208       24.27  2.03    Male    Yes   Sat  Dinner     2
210       30.06  2.00    Male    Yes   Sat  Dinner     3
229       22.12  2.88  Female    Yes   Sat  Dinner     2
230       24.01  2.00    Male    Yes   Sat  Dinner     4
237       32.83  1.17    Male    Yes   Sat  Dinner     2
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2

## Task 2: Select Only Relevant Columns

In [8]:
relevant_cols = ['total_bill', 'tip', 'sex', 'day', 'time', 'size']
subset = filtered_df[relevant_cols].copy()


print('Subset shape:', subset.shape)
subset

Subset shape: (21, 6)

     total_bill   tip     sex   day    time  size
21        20.29  2.75  Female   Sat  Dinner     2
33        20.69  2.45  Female   Sat  Dinner     4
48        28.55  2.05    Male   Sun  Dinner     3
57        26.41  1.50  Female   Sat  Dinner     2
68        20.23  2.01    Male   Sat  Dinner     2
102       44.30  2.50  Female   Sat  Dinner     3
113       23.95  2.55    Male   Sun  Dinner     2
119       24.08  2.92  Female  Thur   Lunch     4
129       22.82  2.18    Male  Thur   Lunch     3
131       20.27  2.83  Female  Thur   Lunch     2
153       24.55  2.00    Male   Sun  Dinner     4
166       20.76  2.24    Male   Sun  Dinner     2
187       30.46  2.00    Male   Sun  Dinner     5
192       28.44  2.56    Male  Thur   Lunch     2
208       24.27  2.03    Male   Sat  Dinner     2
210       30.06  2.00    Male   Sat  Dinner     3
229       22.12  2.88  Female   Sat  Dinner     2
230       24.01  2.00    Male   Sat  Dinner     4
237       32.83  1.17    Male   Sat  Dinner     2
240       27.18  2.00  Female   Sat  Dinner     2
241       22.67  2.00    Male   Sat  Dinner     2

## Task 3: Analyze — Is This Segment Under-Tipping?

In [14]:
# Compute tip % for full dataset baseline
subset['tip_percentage'] = (subset['tip'] / subset['total_bill'] * 100).round(2)

tips['tip_percentage'] = (tips['tip'] / tips['total_bill'] * 100).round(2)

overall_avg_tip_amt  = tips['tip'].mean()
segment_avg_tip_amt  = subset['tip'].mean()

print('=== Under-Tipping Analysis ===')
print(f'Overall avg tip ($) : ${overall_avg_tip_amt:.2f}')
print(f'Segment avg tip ($) : ${segment_avg_tip_amt:.2f}')

if segment_avg_tip_amt < overall_avg_tip_amt:
    print(f'\nThis segment IS under-tipping by {overall_avg_tip_amt - segment_avg_tip_amt:.2f}')
else:
    print('\nThis segment is tipping normally or above average.')

=== Under-Tipping Analysis ===
Overall avg tip ($) : $3.00
Segment avg tip ($) : $2.22

This segment IS under-tipping by 0.78