# Q13. Custom Feature Transformation using apply()
**Context:** Real ML requires custom logic transformation.
**Dataset:** Titanic

In [2]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

titanic = sns.load_dataset('titanic')
print('Shape:', titanic.shape)
titanic[['age', 'survived']].head(8)

Shape: (891, 15)

    age  survived
0  22.0         0
1  38.0         1
2  26.0         1
3  35.0         1
4  35.0         0
5   NaN         0
6  54.0         0
7   2.0         0

## Task 1 & 2: Create age_group using .apply()

In [6]:
def classify_age(age):
    if age < 18:
        return 'Child'
    elif age < 60:
        return 'Adult'
    else:
        return 'Senior'

df['age_group'] = df['age'].apply(classify_age)

print(df['age_group'].value_counts())
print()
df[['age', 'age_group', 'survived']].head(10)

age_group distribution:
age_group
Adult     575
Child     113
Senior     26
Name: count, dtype: int64

     age age_group  survived
0   22.0     Adult         0
1   38.0     Adult         1
2   26.0     Adult         1
3   35.0     Adult         1
4   35.0     Adult         0
6   54.0     Adult         0
7    2.0     Child         0
8   27.0     Adult         1
9   14.0     Child         1
10   4.0     Child         1

## Task 3: Compute Survival Rate per Group

In [8]:
survival_by_group = df.groupby('age_group').agg(
    total       =('survived', 'count'),
    survived    =('survived', 'sum'),
    survival_rate=('survived', 'mean')
).round(3)

survival_by_group['survival_rate_%'] = (survival_by_group['survival_rate'] * 100).round(1)
survival_by_group = survival_by_group.sort_values('survival_rate_%', ascending=True)

print('Survival Rate by Age Group:')
print(survival_by_group)

Survival Rate by Age Group:
           total  survived  survival_rate  survival_rate_%
age_group
Senior        26         7          0.269             26.9
Adult        575       222          0.386             38.6
Child        113        61          0.540             54.0